#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""nodi-edge installer script."""
from __future__ import annotations

import subprocess
import sys
import os
import pwd
import grp
import getpass
from pathlib import Path


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Constants
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

USER_NODI = "nodi"
USER_GUEST = "guest"

DATA_DIR = Path("/home/nodi/nodi-edge-data")
GUEST_BIN_DIR = Path("/home/guest/bin")
SUDOERS_FILE = Path("/etc/sudoers.d/nodi-edge")

GUEST_ALLOWED_COMMANDS = [
    "/usr/bin/ping",
    "/usr/bin/ip",
    "/usr/bin/netstat",
    "/usr/bin/traceroute",
    "/usr/bin/ss",
    "/usr/bin/df",
    "/usr/bin/free",
    "/usr/bin/uptime",
    "/usr/bin/ps",
    "/usr/bin/top",
    "/usr/bin/vmstat",
    "/usr/bin/iostat",
    "/usr/bin/w",
    "/usr/bin/who",
    "/usr/bin/grep",
    "/usr/bin/exit",
]


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Helper Functions
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    print(f"  > {' '.join(cmd)}")
    return subprocess.run(cmd, check=check, capture_output=True, text=True)


def user_exists(username: str) -> bool:
    try:
        pwd.getpwnam(username)
        return True
    except KeyError:
        return False


def prompt_password(username: str) -> str:
    while True:
        pw1 = getpass.getpass(f"  Enter password for '{username}': ")
        pw2 = getpass.getpass(f"  Confirm password for '{username}': ")
        if pw1 == pw2:
            return pw1
        print("  Passwords do not match. Try again.")


def set_password(username: str, password: str) -> None:
    proc = subprocess.Popen(["chpasswd"],
                            stdin=subprocess.PIPE,
                            stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE)
    proc.communicate(input=f"{username}:{password}".encode())


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Check root privilege
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

if os.geteuid() != 0:
    print("Error: This script must be run as root.")
    print("Usage: sudo python3 install.py")
    sys.exit(1)

print("=" * 60)
print("nodi-edge Installer")
print("=" * 60)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# [1/5] Setup nodi user
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

print("\n[1/5] Setting up 'nodi' user...")

if user_exists(USER_NODI):
    print(f"  User '{USER_NODI}' already exists. Skipping creation.")
else:
    run(["useradd", "-m", "-s", "/bin/bash", USER_NODI])
    print(f"  User '{USER_NODI}' created.")

    password = prompt_password(USER_NODI)
    set_password(USER_NODI, password)
    print(f"  Password set for '{USER_NODI}'.")

# Restrict nodi home directory (prevent guest access)
nodi_home = Path(f"/home/{USER_NODI}")
run(["chmod", "750", str(nodi_home)])
print(f"  Home directory restricted (750, no access for others).")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# [2/5] Setup guest user
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

print("\n[2/5] Setting up 'guest' user...")

if user_exists(USER_GUEST):
    print(f"  User '{USER_GUEST}' already exists. Skipping creation.")
else:
    run(["useradd", "-m", "-s", "/bin/rbash", USER_GUEST])
    print(f"  User '{USER_GUEST}' created with restricted shell.")

    password = prompt_password(USER_GUEST)
    set_password(USER_GUEST, password)
    print(f"  Password set for '{USER_GUEST}'.")

# Create bin directory for allowed commands
GUEST_BIN_DIR.mkdir(parents=True, exist_ok=True)

# Clear old symlinks and re-create (force re-apply)
for existing in GUEST_BIN_DIR.iterdir():
    if existing.is_symlink():
        existing.unlink()
print("  Cleared old command links.")

# Link allowed commands
for cmd_path in GUEST_ALLOWED_COMMANDS:
    cmd = Path(cmd_path)
    if cmd.exists():
        link_path = GUEST_BIN_DIR / cmd.name
        link_path.symlink_to(cmd)
        print(f"  Linked: {cmd.name}")
    else:
        print(f"  Warning: {cmd_path} not found, skipping.")

# Unlock .bashrc if immutable (for re-apply)
bashrc_path = Path(f"/home/{USER_GUEST}/.bashrc")
run(["chattr", "-i", str(bashrc_path)], check=False)

# Overwrite .bashrc with restricted PATH
bashrc_path.write_text(f"# Restricted PATH (auto-generated by install.py)\nexport PATH={GUEST_BIN_DIR}\n")
print("  .bashrc configured with restricted PATH.")

# Make .bashrc immutable
run(["chattr", "+i", str(bashrc_path)], check=False)
print("  .bashrc locked (immutable).")

# Make home directory read-only for guest (force re-apply)
guest_home = Path(f"/home/{USER_GUEST}")
run(["chown", "root:root", str(guest_home)])
run(["chmod", "755", str(guest_home)])
print("  Home directory set to read-only (owned by root).")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# [3/5] Setup data directory
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

print("\n[3/5] Setting up data directory...")

dirs = [
    DATA_DIR / "backup",
    DATA_DIR / "config" / "apps",
    DATA_DIR / "config" / "interfaces",
    DATA_DIR / "data" / "snapshots",
    DATA_DIR / "log",
]

for d in dirs:
    d.mkdir(parents=True, exist_ok=True)
    print(f"  Created: {d}")

# Set ownership to nodi (force re-apply)
uid = pwd.getpwnam(USER_NODI).pw_uid
gid = grp.getgrnam(USER_NODI).gr_gid

def chown_recursive(path: Path, uid: int, gid: int) -> None:
    os.chown(path, uid, gid)
    for child in path.rglob("*"):
        os.chown(child, uid, gid)

chown_recursive(DATA_DIR, uid, gid)
print(f"  Ownership set to '{USER_NODI}' (recursive).")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# [4/5] Setup sudoers for nodi
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

print("\n[4/5] Setting up sudoers for 'nodi'...")

sudoers_content = """# nodi-edge service management (auto-generated by install.py)
# Allow nodi to manage nodi-edge services without password

nodi ALL=(root) NOPASSWD: /usr/bin/systemctl start ne-*
nodi ALL=(root) NOPASSWD: /usr/bin/systemctl stop ne-*
nodi ALL=(root) NOPASSWD: /usr/bin/systemctl restart ne-*
nodi ALL=(root) NOPASSWD: /usr/bin/systemctl status ne-*
nodi ALL=(root) NOPASSWD: /usr/bin/systemctl enable ne-*
nodi ALL=(root) NOPASSWD: /usr/bin/systemctl disable ne-*
nodi ALL=(root) NOPASSWD: /usr/bin/systemctl daemon-reload
nodi ALL=(root) NOPASSWD: /usr/bin/journalctl -u ne-*
"""

SUDOERS_FILE.write_text(sudoers_content)
run(["chmod", "440", str(SUDOERS_FILE)])
print(f"  Created: {SUDOERS_FILE}")
print("  nodi can now manage ne-* services without password.")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# [5/5] Summary
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

print("\n[5/5] Installation complete!")
print("\n" + "=" * 60)
print("SUMMARY")
print("=" * 60)
print("""
Account Structure:
┌─────────────────────────────────────────────────────────┐
│ guest (restricted)                                      │
│ - SSH login: ssh guest@<host>                           │
│ - Network: ping, ip, netstat, traceroute, ss            │
│ - System: df, free, uptime, ps, top, vmstat, iostat, w  │
│ - Cannot switch to other users                          │
│ - Home directory is read-only                           │
└─────────────────────────────────────────────────────────┘

┌─────────────────────────────────────────────────────────┐
│ nodi (service account)                                  │
│ - SSH login: ssh nodi@<host>                            │
│ - Service management (sudo systemctl start/stop ne-*)   │
│ - Config editing, log access                            │
│ - Can switch to root: su root                           │
└─────────────────────────────────────────────────────────┘

┌─────────────────────────────────────────────────────────┐
│ root (admin)                                            │
│ - Access via: su root (from nodi account)               │
│ - Full system access                                    │
└─────────────────────────────────────────────────────────┘

Data Directory:
  /home/nodi/nodi-edge-data/
  ├── backup/              # Cloud sync target
  ├── config/
  │   ├── apps/            # App-specific settings
  │   └── interfaces/      # Interface config files
  ├── data/
  │   └── snapshots/       # Databus snapshots
  └── log/                 # Log files

Sudoers (nodi can run without password):
  sudo systemctl start|stop|restart|status|enable|disable ne-*
  sudo systemctl daemon-reload
  sudo journalctl -u ne-*
""")
